src/main/java/com/denimgroup/threadfix/data/entities/Organization.java
////////////////////////////////////////////////////////////////////////
//
//     Copyright (c) 2009-2011 Denim Group, Ltd.
//
//     The contents of this file are subject to the Mozilla Public License
//     Version 1.1 (the "License"); you may not use this file except in
//     compliance with the License. You may obtain a copy of the License at
//     http://www.mozilla.org/MPL/
//
//     Software distributed under the License is distributed on an "AS IS"
//     basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
//     License for the specific language governing rights and limitations
//     under the License.
//
//     The Original Code is Vulnerability Manager.
//
//     The Initial Developer of the Original Code is Denim Group, Ltd.
//     Portions created by Denim Group, Ltd. are Copyright (C)
//     Denim Group, Ltd. All Rights Reserved.
//
//     Contributor(s): Denim Group, Ltd.
//
////////////////////////////////////////////////////////////////////////
package com.denimgroup.threadfix.data.entities;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.Size;

import org.codehaus.jackson.annotate.JsonIgnore;
import org.hibernate.validator.constraints.NotEmpty;

@Entity
@Table(name = "Organization")
public class Organization extends AuditableEntity {

	private static final long serialVersionUID = 6734388139007659988L;
	
	private List<Application> activeApps;
	
	public static final int NAME_LENGTH = 60;

	@NotEmpty(message = "{errors.required}")
	@Size(max = NAME_LENGTH, message = "{errors.maxlength} " + NAME_LENGTH + ".")
	private String name;

	private List<Application> applications;
	private List<SurveyResult> surveyResults;

	@Column(length = NAME_LENGTH, nullable = false)
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(mappedBy = "organization")
	@OrderBy("name")
	public List<Application> getApplications() {
		return applications;
	}

	public void setApplications(List<Application> applications) {
		this.applications = applications;
	}

	@OneToMany(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, mappedBy = "organization")
	@OrderBy("createdDate DESC")
	public List<SurveyResult> getSurveyResults() {
		return surveyResults;
	}

	public void setSurveyResults(List<SurveyResult> surveyResults) {
		this.surveyResults = surveyResults;
	}
	
	@Transient
	@JsonIgnore
	public List<Application> getActiveApplications() {
		if (activeApps == null) {
			activeApps = new ArrayList<Application>();
			for (Application application : this.applications) {
				if (application.isActive())
					activeApps.add(application);
			}
		}
		return activeApps;
	}

	// TODO this might belong somewhere else
	/*
	 * Index Severity 0 Info 1 Low 2 Medium 3 High 4 Critical 5 # Total vulns
	 */
	@Transient
	@JsonIgnore
	public List<Integer> getVulnerabilityReport() {

		int[] calculations = new int[6];
		for (int i = 0; i < calculations.length; i++) {
			calculations[i] = 0;
		}

		for (Application app : this.applications) {
			if (app == null || !app.isActive())
				continue;
			
			for (int i = 0; i < calculations.length; i++) {
				calculations[i] += app.getVulnerabilityReport().get(i);
			}
		}

		List<Integer> retVal = new ArrayList<Integer>();
		for (int i = 0; i < calculations.length; i++) {
			retVal.add(Integer.valueOf(calculations[i]));
		}

		return retVal;
	}

}

src/main/java/com/denimgroup/threadfix/webapp/controller/ReportsController.java
////////////////////////////////////////////////////////////////////////
//
//     Copyright (c) 2009-2011 Denim Group, Ltd.
//
//     The contents of this file are subject to the Mozilla Public License
//     Version 1.1 (the "License"); you may not use this file except in
//     compliance with the License. You may obtain a copy of the License at
//     http://www.mozilla.org/MPL/
//
//     Software distributed under the License is distributed on an "AS IS"
//     basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
//     License for the specific language governing rights and limitations
//     under the License.
//
//     The Original Code is Vulnerability Manager.
//
//     The Initial Developer of the Original Code is Denim Group, Ltd.
//     Portions created by Denim Group, Ltd. are Copyright (C)
//     Denim Group, Ltd. All Rights Reserved.
//
//     Contributor(s): Denim Group, Ltd.
//
////////////////////////////////////////////////////////////////////////
package com.denimgroup.threadfix.webapp.controller;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.servlet.ServletOutputStream;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.support.SessionStatus;

import com.denimgroup.threadfix.data.entities.Application;
import com.denimgroup.threadfix.data.entities.ApplicationChannel;
import com.denimgroup.threadfix.data.entities.Finding;
import com.denimgroup.threadfix.data.entities.Organization;
import com.denimgroup.threadfix.data.entities.ReportParameters;
import com.denimgroup.threadfix.data.entities.Vulnerability;
import com.denimgroup.threadfix.service.ApplicationService;
import com.denimgroup.threadfix.service.OrganizationService;
import com.denimgroup.threadfix.service.report.ReportsService;

@Controller
@RequestMapping("/reports")
public class ReportsController {
	
	private final Log log = LogFactory.getLog(ReportsController.class);

	private OrganizationService organizationService;
	private ApplicationService applicationService;
	private ReportsService reportsService;

	@Autowired
	public ReportsController(OrganizationService organizationService,
			ApplicationService applicationService, ReportsService reportsService) {
		this.organizationService = organizationService;
		this.applicationService = applicationService;
		this.reportsService = reportsService;
	}

	@ModelAttribute("organizationList")
	public List<Organization> getOrganizations() {
		List<Organization> organizationList = organizationService.loadAll();
		return organizationList;
	}

	@RequestMapping(method = RequestMethod.GET)
	public String index(ModelMap model, HttpServletRequest request) {
		
		if (request != null && request.getSession() != null && request.getSession().getAttribute("reportsError") != null) {
			model.addAttribute("error", request.getSession().getAttribute("reportsError"));
			request.getSession().removeAttribute("reportsError");
		}
		
		model.addAttribute(new ReportParameters());
		return "reports/index";
	}

	@RequestMapping(method = RequestMethod.POST)
	public String processSubmit(ModelMap model, @ModelAttribute ReportParameters reportParameters,
			BindingResult result, SessionStatus status, HttpServletRequest request, HttpServletResponse response) throws IOException{
		String reportFile = null;

		if (reportParameters.getReportId() < 0 || reportParameters.getReportId() > 7) {
			log.warn("An incorrect report ID was passed through, returning an error page.");
			request.getSession().setAttribute("reportsError", "An invalid report type was chosen.");
			return "redirect:/reports";
		}
		
		List<Integer> applicationIdList = getApplicationIdList(reportParameters);

		if (applicationIdList == null || applicationIdList.isEmpty()) {
			request.getSession().setAttribute("reportsError", "You must select at least one application.");
			return "redirect:/reports";
		}
		
		switch (reportParameters.getReportId()) {
		case 1:
			reportFile = "trending.jrxml";
			break;
		case 2:
			reportFile = "pointInTime.jrxml";
			break;
		case 3:
			reportFile = "cwe.jrxml";
			break;
		case 4:
			reportFile = "cweChannel.jrxml";
			break;
		case 5:
			reportFile = "scannerComparison.jrxml";
			break;
		case 6:
			return scannerComparisonByVulnerability(model, applicationIdList);
		case 7:
			reportFile = "monthlyBarChart.jrxml";
		}

		log.info("About to generate report for " + applicationIdList.size() + " applications.");

		Map<String, Object> params = new HashMap<String, Object>();
		params.put("appId", applicationIdList);
		String path = request.getSession().getServletContext().getRealPath("/");
		StringBuffer report = null;
		
		if(reportParameters.getFormatId() == 2) {
			report = reportsService.getReport(path, reportFile, "CSV", params, applicationIdList, response);
			String pageString = report.toString();
			response.setContentType("application/octet-stream");
			response.setHeader("Content-Disposition", "attachment; filename=\"report_csv_" + applicationIdList
					+ ".txt\"");

			ServletOutputStream out = response.getOutputStream();

			InputStream in = new ByteArrayInputStream(pageString.getBytes("UTF-8"));

			byte[] outputByte = new byte[65535];
			
			int remainingSize = in.read(outputByte, 0, 65535);
			
			// copy binary contect to output stream
			while (remainingSize != -1) {
				out.write(outputByte, 0, remainingSize);
				remainingSize = in.read(outputByte, 0, 65535);
			}
			in.close();
			out.flush();
			out.close();
			return null;
		
		} else if(reportParameters.getFormatId() == 3) {
			report = reportsService.getReport(path, reportFile, "PDF", params, applicationIdList, response);
			return null;
			
		} else //Output is HTML
			report = reportsService.getReport(path, reportFile, "HTML", params, applicationIdList, response);
		
		model.addAttribute("jasperReport", report);
		
		if (report != null) {
			log.info("Finished generating report.");
			return "reports/report";
		} else {
			log.warn("Failed to generate report.");
			request.getSession().setAttribute("reportsError", "There was an error generating the report.");
			return "redirect:/reports";
		}
	}
	
	public List<Integer> getApplicationIdList(ReportParameters reportParameters) {
		List<Integer> applicationIdList = new ArrayList<Integer>();
		
		if (reportParameters.getOrganizationId() < 0) {
			if (reportParameters.getApplicationId() < 0) {
				List<Application> appList = applicationService.loadAll();
				for (Application app : appList) {
					if (app.isActive()) {
						applicationIdList.add(app.getId());
					}
				}
			} else {
				applicationIdList.add(reportParameters.getApplicationId());
			}
		} else {
			Organization org = organizationService.loadOrganization(reportParameters.getOrganizationId());
			if (reportParameters.getApplicationId() < 0) {
				List<Application> appList = org.getActiveApplications();
				for (Application app : appList) {
					if (app.isActive()) {
						applicationIdList.add(app.getId());
					}
				}
			} else {
				applicationIdList.add(reportParameters.getApplicationId());
			}
		}
		
		return applicationIdList;
	}
	
	
	// TODO rethink some of this - it's a little slow at a few hundred vulns. 
	// The emphasis on genericism through the design makes it harder to pull channel-specific info from vulns.
	public String scannerComparisonByVulnerability(ModelMap model, List<Integer> applicationIdList) {		
		
		if (model == null || applicationIdList == null || applicationIdList.isEmpty()) {
			// This should have been caught earlier
			return "redirect:/reports";
		}
		
		List<List<String>> tableListOfLists = new ArrayList<List<String>>();
		List<String> headerList = new ArrayList<String>(); // this facilitates headers
		List<Application> applicationList = new ArrayList<Application>();
		
		// this map is used to insert the value into the correct space.
		Map<Integer, Integer> channelIdToTablePositionMap = new HashMap<Integer, Integer>();
		
		// positions 0, 1, and 2 are the generic name, path, and parameter of the vulnerability.
		// 3 is open status
		// This also represents the number of headers.
		int columnCount = 4;
				
		for (int id : applicationIdList) {
			Application application = applicationService.loadApplication(id);
			
			if (application == null || application.getChannelList() == null 
					|| application.getVulnerabilities() == null)
				continue;
			applicationList.add(application);
						
			for (ApplicationChannel channel : application.getChannelList()) {
				if (channel == null || channel.getScanCounter() == null
						|| channel.getChannelType() == null 
						|| channel.getChannelType().getId() == null
						|| channel.getChannelType().getName() == null)
					continue;
				
				int channelTypeId = channel.getChannelType().getId();
				
				if (!channelIdToTablePositionMap.containsKey(channelTypeId)) {
					headerList.add(channel.getChannelType().getName());
					channelIdToTablePositionMap.put(channelTypeId, columnCount++);
				}
			}
		}
		
		for (Application application : applicationList) {
			for (Vulnerability vuln : application.getVulnerabilities()) {
				if (vuln == null || vuln.getFindings() == null
						|| (!vuln.isActive() && !vuln.getIsFalsePositive())) {
					continue;
				}
				

src/main/webapp/WEB-INF/views/reports/index.jsp
<%@ include file="/common/taglibs.jsp"%>

<head>
	<title>Reports</title>
	
	<script type="text/javascript">
	$(document).ready(function(){ 
		$("#orgSelect").change(function() {
			$("#appSelect").html('');
			$("#appSelect").append('<option value="-1">All</option>');
			var options = '';
			
			<c:forEach var="organization" items="${organizationList}">
			    if("${organization.id}" == $("#orgSelect").val()) {
					<c:forEach var="application" items="${ organization.activeApplications}">
						options += '<option value="${ application.id}"><c:out value="${ application.name }"/></option>';
					</c:forEach>
			    } 
			</c:forEach>

			$("#appSelect").append(options);
		});
	});
	</script>

</head>

<body id="reports">
	<h2>Reports</h2>
	
	<c:if test="${ not empty error }">
		<center class="errors" ><c:out value="${ error }"/></center>
	</c:if>

	<spring:url value="" var="emptyUrl"></spring:url>	
	<form:form modelAttribute="reportParameters" action="${ fn:escapeXml(emptyUrl) }">
		<table class="dataTable">
			<tbody>
				<tr>
					<td class="label">Report:</td>
					<td class="inputValue">
						<div id="rptDrowDown">
							<form:select path="reportId">
								<option value="1">Trending Report</option>
								<option value="2">Point in Time Report</option>
								<option value="3">Vulnerability Progress By Type</option>
								<option value="4">Channel Comparison By Vulnerability Types</option>
								<option value="5">Channel Comparison Summary</option>
								<option value="6">Channel Comparison Detail</option>
								<option value="7">Monthly Progress Report</option>
							</form:select>
						</div>
					</td>
				</tr>
				<tr>
					<td class="label">Team:</td>
					<td class="inputValue">
						<div id="orgDropDown">
							<form:select path="organizationId" id="orgSelect">
								<option value="-1">All</option>
								<c:forEach var="organization" items="${ organizationList }">
									<c:if test="${ organization.active }">
									<option value="${ organization.id }">
										<c:out value="${ organization.name }"/>
									</option>
									</c:if>
								</c:forEach>
							</form:select>
						</div>
					</td>
				</tr>
				<tr>
					<td class="label">Application:</td>
					<td class="inputValue">
						<div id="appDropDown">
							<form:select path="applicationId" id="appSelect">
								<option value="-1">All</option>
							</form:select>
							<form:errors path="applicationId"/>
						</div>
					</td>
				</tr>
				<tr>
					<td class="label">Format:</td>
					<td class="inputValue">
						<div id="formatDropDown">
							<form:select path="formatId">
								<option value="1">HTML</option>
								<option value="2">CSV</option>
								<option value="3">PDF</option>
							</form:select>
							<form:errors path="formatId"/>
						</div>
					</td>
				</tr>
			</tbody>
		</table>
		<br />
		<input type="submit" value="Run Report" />
	</form:form>
</body>

src/main/webapp/WEB-INF/views/reports/report.jsp
<%@ include file="/common/taglibs.jsp"%>

<head>
	<title>Report</title>
</head>

<body id="reports">
	<h2>Report</h2>
	
	${jasperReport}
</body>

src/main/webapp/WEB-INF/views/reports/scannerComparisonByVulnerability.jsp
<%@ include file="/common/taglibs.jsp"%>

<head>
	<title>Scanner Comparison By Vulnerability</title>
	<script type="text/javascript" src="<%=request.getContextPath()%>/scripts/confirm.js"></script>
	<script type="text/javascript" src="<%=request.getContextPath()%>/scripts/sortable_us.js"></script>
	<script type="text/javascript" language="javascript" src="<%=request.getContextPath()%>/scripts/tablefilter2.js"></script> 
	<style type="text/css">
		input {width:100%}
	</style>
</head>

<body>
	<h2>Channel Comparison Detail</h2>
	
	The boxes at the top are filters. To use them, enter the search text for the column and press the Enter key.<br/><br/>

	<table class="sortable filteredTable" id="table1">
		<thead>
			<tr class="darkBackground">
				<th class="first">Vulnerability Name</th>
				<th>Path</th>
				<th>Parameter</th>
				<th>Status</th>
				<c:forEach var="item" items="${headerList}">
					<th><c:out value="${ item }"/></th>
				</c:forEach>
			</tr>
		</thead>
		
		<tbody>
		<c:forEach var="rowList" items="${listOfLists}">
			<tr class="bodyRow">
				<c:forEach var="item" items="${rowList}">
					<td><c:out value="${ item }"/></td>
				</c:forEach>
			</tr>
		</c:forEach>
		</tbody>
	</table>
	<script language="javascript" type="text/javascript">  
    	var tf = setFilterGrid("table1");  
	</script> 
</body>