src/main/java/com/denimgroup/threadfix/data/entities/BaseEntity.java
////////////////////////////////////////////////////////////////////////
//
//     Copyright (c) 2009-2011 Denim Group, Ltd.
//
//     The contents of this file are subject to the Mozilla Public License
//     Version 1.1 (the "License"); you may not use this file except in
//     compliance with the License. You may obtain a copy of the License at
//     http://www.mozilla.org/MPL/
//
//     Software distributed under the License is distributed on an "AS IS"
//     basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
//     License for the specific language governing rights and limitations
//     under the License.
//
//     The Original Code is Vulnerability Manager.
//
//     The Initial Developer of the Original Code is Denim Group, Ltd.
//     Portions created by Denim Group, Ltd. are Copyright (C)
//     Denim Group, Ltd. All Rights Reserved.
//
//     Contributor(s): Denim Group, Ltd.
//
////////////////////////////////////////////////////////////////////////
package com.denimgroup.threadfix.data.entities;

import java.io.Serializable;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;
import javax.persistence.Transient;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * A base class for all entities that ensures Serialization and PK generation.
 * 
 * A primer on annotations is below. More information can be obtained from the
 * Hibernate docs here:
 * 
 * http://docs.jboss.org/hibernate/stable/annotations/reference/en/html_single/
 * 
 * @Column( name="columnName"; (1) boolean unique() default false; (2) boolean
 *          nullable() default true; (3) boolean insertable() default true; (4)
 *          boolean updatable() default true; (5) String columnDefinition()
 *          default ""; (6) String table() default ""; (7) int length() default
 *          255; (8) int precision() default 0; // decimal precision (9) int
 *          scale() default 0; // decimal scale
 * 
 * @author bbeverly
 * 
 */
@MappedSuperclass
public class BaseEntity implements Serializable {

	private static final long serialVersionUID = 1L;

	private Integer id = null;

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Transient
	@JsonIgnore
	public boolean isNew() {
		return this.getId() == null;
	}
}

src/main/java/com/denimgroup/threadfix/data/entities/Waf.java
////////////////////////////////////////////////////////////////////////
//
//     Copyright (c) 2009-2011 Denim Group, Ltd.
//
//     The contents of this file are subject to the Mozilla Public License
//     Version 1.1 (the "License"); you may not use this file except in
//     compliance with the License. You may obtain a copy of the License at
//     http://www.mozilla.org/MPL/
//
//     Software distributed under the License is distributed on an "AS IS"
//     basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
//     License for the specific language governing rights and limitations
//     under the License.
//
//     The Original Code is Vulnerability Manager.
//
//     The Initial Developer of the Original Code is Denim Group, Ltd.
//     Portions created by Denim Group, Ltd. are Copyright (C)
//     Denim Group, Ltd. All Rights Reserved.
//
//     Contributor(s): Denim Group, Ltd.
//
////////////////////////////////////////////////////////////////////////
package com.denimgroup.threadfix.data.entities;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.Size;

import org.codehaus.jackson.annotate.JsonIgnore;
import org.hibernate.validator.constraints.NotEmpty;

@Entity
@Table(name = "Waf")
public class Waf extends AuditableEntity {

	private static final long serialVersionUID = 2937339816996157154L;

	public static final int NAME_LENGTH = 50;
	
	@NotEmpty(message = "{errors.required}")
	@Size(max = NAME_LENGTH, message = "{errors.maxlength} " + NAME_LENGTH + ".")
	private String name;
	private WafType wafType;
	private Integer currentId;
	private WafRuleDirective lastWafRuleDirective;

	private List<Application> applicationList;
	private List<WafRule> wafRuleList;

	@Column(length = NAME_LENGTH, nullable = false)
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	@Column
	public Integer getCurrentId() {
		return currentId;
	}

	public void setCurrentId(Integer currentId) {
		this.currentId = currentId;
	}

	@ManyToOne
	@JoinColumn(name = "wafTypeId")
	public WafType getWafType() {
		return wafType;
	}

	public void setWafType(WafType wafType) {
		this.wafType = wafType;
	}
	
	@ManyToOne
	@JoinColumn(name = "wafRuleDirectiveId")
	public WafRuleDirective getLastWafRuleDirective() {
		return lastWafRuleDirective;
	}

	public void setLastWafRuleDirective(WafRuleDirective lastWafRuleDirective) {
		this.lastWafRuleDirective = lastWafRuleDirective;
	}

	@OneToMany(mappedBy = "waf")
	@JsonIgnore
	public List<Application> getApplications() {
		return applicationList;
	}

	public void setApplications(List<Application> applicationList) {
		this.applicationList = applicationList;
	}

	@OneToMany(mappedBy = "waf")
	public List<WafRule> getWafRules() {
		return wafRuleList;
	}

	public void setWafRules(List<WafRule> wafRuleList) {
		this.wafRuleList = wafRuleList;
	}

}

src/main/java/com/denimgroup/threadfix/data/entities/WafType.java
////////////////////////////////////////////////////////////////////////
//
//     Copyright (c) 2009-2011 Denim Group, Ltd.
//
//     The contents of this file are subject to the Mozilla Public License
//     Version 1.1 (the "License"); you may not use this file except in
//     compliance with the License. You may obtain a copy of the License at
//     http://www.mozilla.org/MPL/
//
//     Software distributed under the License is distributed on an "AS IS"
//     basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
//     License for the specific language governing rights and limitations
//     under the License.
//
//     The Original Code is Vulnerability Manager.
//
//     The Initial Developer of the Original Code is Denim Group, Ltd.
//     Portions created by Denim Group, Ltd. are Copyright (C)
//     Denim Group, Ltd. All Rights Reserved.
//
//     Contributor(s): Denim Group, Ltd.
//
////////////////////////////////////////////////////////////////////////
package com.denimgroup.threadfix.data.entities;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.Size;

import org.codehaus.jackson.annotate.JsonIgnore;
import org.hibernate.validator.constraints.NotEmpty;

@Entity
@Table(name = "WafType")
public class WafType extends BaseEntity {

	private static final long serialVersionUID = 2937339816996157154L;

	public static final String MOD_SECURITY = "mod_security";
	public static final String SNORT = "Snort";
	public static final String BIG_IP_ASM = "BIG-IP ASM";
	
	@NotEmpty(message = "{errors.required}")
	@Size(max = 50, message = "{errors.maxlength}")
	private String name;
	
	private Integer initialId;

	private List<Waf> wafs;
	private List<WafRuleDirective> wafRuleDirectives;


	@Column(length = 50, nullable = false)
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	@Column
	public Integer getInitialId() {
		if (initialId == null)
			setInitialId(100000);
		
		return initialId;
	}

	public void setInitialId(Integer initialId) {
		this.initialId = initialId;
	}

	@OneToMany(mappedBy = "wafType")
	@JsonIgnore
	public List<Waf> getWafs() {
		return wafs;
	}

	public void setWafs(List<Waf> wafs) {
		this.wafs = wafs;
	}
	
	@OneToMany(mappedBy = "wafType")
	@JsonIgnore
	public List<WafRuleDirective> getWafRuleDirectives() {
		return wafRuleDirectives;
	}

	public void setWafRuleDirectives(List<WafRuleDirective> wafRuleDirectives) {
		this.wafRuleDirectives = wafRuleDirectives;
	}
}

src/main/java/com/denimgroup/threadfix/webapp/controller/WafsController.java
////////////////////////////////////////////////////////////////////////
//
//     Copyright (c) 2009-2011 Denim Group, Ltd.
//
//     The contents of this file are subject to the Mozilla Public License
//     Version 1.1 (the "License"); you may not use this file except in
//     compliance with the License. You may obtain a copy of the License at
//     http://www.mozilla.org/MPL/
//
//     Software distributed under the License is distributed on an "AS IS"
//     basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
//     License for the specific language governing rights and limitations
//     under the License.
//
//     The Original Code is Vulnerability Manager.
//
//     The Initial Developer of the Original Code is Denim Group, Ltd.
//     Portions created by Denim Group, Ltd. are Copyright (C)
//     Denim Group, Ltd. All Rights Reserved.
//
//     Contributor(s): Denim Group, Ltd.
//
////////////////////////////////////////////////////////////////////////
package com.denimgroup.threadfix.webapp.controller;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.List;

import javax.servlet.ServletOutputStream;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.support.SessionStatus;
import org.springframework.web.servlet.ModelAndView;

import com.denimgroup.threadfix.data.entities.Application;
import com.denimgroup.threadfix.data.entities.Waf;
import com.denimgroup.threadfix.data.entities.WafRule;
import com.denimgroup.threadfix.data.entities.WafRuleDirective;
import com.denimgroup.threadfix.data.entities.WafType;
import com.denimgroup.threadfix.service.WafRuleService;
import com.denimgroup.threadfix.service.WafService;
import com.denimgroup.threadfix.service.waf.BigIPASMGenerator;

@Controller
@RequestMapping("/wafs")
public class WafsController {

	private WafService wafService = null;
	private WafRuleService wafRuleService = null;
	
	private final Log log = LogFactory.getLog(WafsController.class);

	@Autowired
	public WafsController(WafService wafService, WafRuleService wafRuleService) {
		this.wafService = wafService;
		this.wafRuleService = wafRuleService;
	}

	@RequestMapping(method = RequestMethod.GET)
	public String index(ModelMap model) {
		model.addAttribute(wafService.loadAll());
		return "wafs/index";
	}

	@RequestMapping("/{wafId}")
	public ModelAndView detail(@PathVariable("wafId") int wafId) {
		ModelAndView mav = new ModelAndView("wafs/detail");
		Waf waf = wafService.loadWaf(wafId);
		
		if (waf == null) {
			log.warn(ResourceNotFoundException.getLogMessage("WAF", wafId));
			throw new ResourceNotFoundException();
		}
		
		mav.addObject(waf);
		List<WafRule> currentRules = wafRuleService.loadCurrentRules(waf);
		mav.addObject("currentRules", currentRules);
		WafRuleDirective lastDirective = null;
		List<WafRuleDirective> directives = null;
		
		if ((waf.getLastWafRuleDirective() != null) && (waf.getWafType().getId().equals(waf.getLastWafRuleDirective().getWafType().getId()))) {
			lastDirective = waf.getLastWafRuleDirective();
			directives = waf.getWafType().getWafRuleDirectives();
			directives.remove(lastDirective);
		} else if (waf.getWafType() != null && waf.getWafType().getWafRuleDirectives() != null && waf.getWafType().getWafRuleDirectives().size() >= 1) {
			lastDirective = waf.getWafType().getWafRuleDirectives().get(0);
			directives = waf.getWafType().getWafRuleDirectives();
			directives.remove(0);
		}
		
		boolean hasApps = false;
		if (waf.getApplications() != null) {
			for (Application application : waf.getApplications()) {
				if (application.isActive()) {
					hasApps = true;
					break;
				}
			}
		}
		
		String prefix = null, suffix = null;
		
		if (WafType.BIG_IP_ASM.equals(waf.getWafType().getName())) {
			prefix = BigIPASMGenerator.XML_START;
			suffix = BigIPASMGenerator.XML_END;
		}
		
		mav.addObject("prefix", prefix);
		mav.addObject("suffix", suffix);
		mav.addObject("hasApps", hasApps);
		mav.addObject("lastDirective", lastDirective);
		mav.addObject("directives", directives);
		
		return mav;
	}

	@RequestMapping("/{wafId}/delete")
	public String deleteWaf(@PathVariable("wafId") int wafId, SessionStatus status) {
		Waf waf = wafService.loadWaf(wafId);
		if (waf != null && (waf.getApplications() == null || waf.getApplications().isEmpty())) {
			wafService.deleteById(wafId);
			status.setComplete();
			return "redirect:/wafs";
		} else {
			log.warn(ResourceNotFoundException.getLogMessage("WAF", wafId));
			throw new ResourceNotFoundException();
		}
	}

	@RequestMapping(value = "/{wafId}", method = RequestMethod.POST)
	public ModelAndView download(@PathVariable("wafId") int wafId, HttpServletRequest request,
			HttpServletResponse response) throws IOException {
		Waf waf = wafService.loadWaf(wafId);
		if (waf == null)
			return null;
		if (waf.getWafRules() == null)
			wafService.generateWafRules(waf, new WafRuleDirective());
		
		StringBuffer buffer = new StringBuffer();
		
		if (WafType.BIG_IP_ASM.equals(waf.getWafType().getName())) {
			buffer.append(BigIPASMGenerator.XML_START);
		}
		
		for (WafRule rule : waf.getWafRules()) {
			buffer.append(rule.getRule()).append("\n");
		}
		
		if (WafType.BIG_IP_ASM.equals(waf.getWafType().getName())) {
			buffer.append(BigIPASMGenerator.XML_END);
		}

		String pageString = buffer.toString();
		response.setContentType("application/octet-stream");
		response.setHeader("Content-Disposition", "attachment; filename=\"wafrules_" + wafId
				+ ".txt\"");

		ServletOutputStream out = response.getOutputStream();
		StringBuffer sb = new StringBuffer();
		sb.append(pageString);

		InputStream in = new ByteArrayInputStream(sb.toString().getBytes("UTF-8"));
		
		byte[] outputByte = new byte[65535];
		
		// copy binary content to output stream
		int numToTransfer = in.read(outputByte, 0, 65535);
		while (numToTransfer != -1) {
			out.write(outputByte, 0, numToTransfer);
			numToTransfer = in.read(outputByte, 0, 65535);
		}
		in.close();
		out.flush();
		out.close();
		return null;
	}
}

src/main/webapp/WEB-INF/views/wafs/detail.jsp
<%@ include file="/common/taglibs.jsp"%>

<head>
	<title><c:out value="${ waf.name }"/></title>
</head>

<body id="wafs">
	<h2 id="nameText" ><c:out value="${ waf.name }"/></h2>
	
	<div id="helpText">
		This page is used to generate rules and upload WAF logs to correlate their results with your existing Vulnerabilities.
		<c:if test="${ empty waf.applications }"><br/>To get started, link this WAF to an application in either the New Application or Edit Application pages.</c:if>
	</div>
	
	<table class="dataTable">
		<tbody>
			<tr>
				<td class="label">Type:</td>
				<td id="wafTypeText" class="inputValue"><c:out value="${ waf.wafType.name }"/></td>
			</tr>
		</tbody>
	</table>
	<br />
	<spring:url value="{wafId}/edit" var="editUrl">
		<spring:param name="wafId" value="${ waf.id }"/>
	</spring:url>
	<a id="editLink" href="${ fn:escapeXml(editUrl) }">Edit WAF</a> | 
	<spring:url value="{wafId}/delete" var="deleteUrl">
		<spring:param name="wafId" value="${ waf.id }"/>
	</spring:url>
	
	<c:if test="${empty waf.applications}">
		<a id="deleteButton" href="${ fn:escapeXml(deleteUrl) }" onclick="return confirm('Are you sure you want to delete this WAF?')">Delete WAF</a> | 
	</c:if>
	<c:if test="${not empty waf.applications}">
		<a id="deleteButton" onclick="return alert('Remove the Applications from this WAF and try again.')">Delete WAF</a> | 
	</c:if>	
	
	<a id="backToListLink" href="<spring:url value="/wafs" />">Back to WAF Index</a>
	
	<br />
	
	<spring:url value="/wafs/${waf.id}/upload" var="uploadUrl">
		<spring:param name="wafId" value="${ waf.id }"/>
	</spring:url>
	<form:form method="post" action="${ fn:escapeXml(uploadUrl) }" enctype="multipart/form-data">
		<form:errors path="*" cssClass="errors" />
		<table class="dataTable">
			<tbody>
				<tr>
					<td class="label">Log File:</td>
					<td class="inputValue">
						<input type="file" name="file" size="50" />
					</td>
				</tr>
			</tbody>
		</table>
		<br />
		<input type="submit" value="Upload File"/>
		<span style="padding-left: 10px"><a href="<spring:url value="/wafs"/>">Cancel</a></span>
	</form:form>
	
	<h3>Applications</h3>
	<table class="formattedTable">
		<thead>
			<tr>
				<th class="medium first">Name</th>
				<th class="long last">URL</th>
			</tr>
		</thead>
		<tbody id="applicationsTableBody">
	<c:choose>
		<c:when test="${ hasApps }">
			<c:forEach var="app" items="${ waf.applications }">
				<c:if test="${ app.active }">
				<tr class="bodyRow">
					<td>
						<spring:url value="/organizations/{orgId}/applications/{appId}" var="appUrl">
							<spring:param name="orgId" value="${ app.organization.id }"/>
							<spring:param name="appId" value="${ app.id }"/>
						</spring:url>
						<a href="${ fn:escapeXml(appUrl) }"><c:out value="${ app.name }"/></a>
					</td>
					<td><c:out value="${ app.url }"/></td>
				</tr>
				</c:if>
			</c:forEach>
		</c:when>
		<c:otherwise>
			<tr class="bodyRow">
				<td colspan="2" style="text-align:center;">No applications found.</td>
			</tr>
		</c:otherwise>
	</c:choose>
			<tr class="footer">
				<td colspan="2" class="pagination last" style="text-align:right"></td>
			</tr>
		</tbody>
	</table>
	
	<spring:url value="/wafs/{wafId}/rules" var="generateRulesUrl">
		<spring:param name="wafId" value="${ waf.id }"/>
	</spring:url>
	<form:form method="post" action="${ fn:escapeXml(generateRulesUrl) }">
	<c:choose>
		<c:when test="${ empty waf.wafType.wafRuleDirectives and empty lastDirective}">
			No Directives Found.  
		</c:when>
		<c:otherwise>
			<select id="wafDirectiveSelect" name="wafDirective" >
				<option value="${ lastDirective.directive }"><c:out value="${ lastDirective.directive }"/></option>
				<c:forEach var="directive" items="${ directives }">
					<option value="${ directive.directive }"><c:out value="${ directive.directive }"/></option>
				</c:forEach>
			</select>
		</c:otherwise>
	</c:choose>
	<input id="generateWafRulesButton" type="submit" value="Generate WAF Rules" />
	</form:form>
	
	<h3>WAF Rule Statistics (click to see details):</h3>
	
	<c:forEach var="wafRule" items="${ waf.wafRules }">
		<spring:url value="/wafs/{wafId}/rules/{wafRuleId}" var="generateRulesUrl">
			<spring:param name="wafId" value="${ waf.id }"/>
			<spring:param name="wafRuleId" value="${ wafRule.id }"/>
		</spring:url>
		<a href="${ fn:escapeXml(generateRulesUrl) }"> <c:out value="${ wafRule.nativeId }"/> - fired <c:out value="${fn:length(wafRule.securityEvents)}" /> times</a>
		<br/>
	</c:forEach>
	
	<h3>WAF Rules:</h3>

	<div id="wafrule">
		<pre>
<c:out value="${ prefix }"/>
<c:forEach var="wafRule" items="${ currentRules }"><c:out value="${ wafRule.rule }"/>
</c:forEach><c:out value="${ suffix }"/>
		</pre>	
	</div>
	<form id="form1" name="form1" method="post">
		<input id="downloadWafRulesButton" type="submit" value="Download Waf Rules"/>
	</form>
</body>

src/main/webapp/WEB-INF/views/wafs/form.jsp
<%@ include file="/common/taglibs.jsp"%>

<head>
	<title><c:if test="${ waf.new }">New </c:if>WAF</title>
</head>

<body id="wafs">
	<h2><c:if test="${ waf.new }">New </c:if>WAF</h2>
	
<spring:url value="" var="emptyUrl"></spring:url>
<form:form modelAttribute="waf" method="post" action="${ fn:escapeXml(emptyUrl) }">
	<table class="dataTable">
		<tbody>
			<tr>
				<td class="label">Name:</td>
				<td class="inputValue">
					<form:input id="nameInput" path="name" cssClass="focus" size="50" maxlength="50"/>
				</td>
				<td style="padding-left: 5px">
					<form:errors path="name" cssClass="errors" />
				</td>
			</tr>
			<tr>
				<td class="label">Type:</td>
				<td class="inputValue">
					<form:select id="typeSelect" path="wafType.id">
						<form:options items="${ wafTypeList }" itemValue="id" itemLabel="name" />
					</form:select>
				</td>
				<td style="padding-left: 5px">
					<form:errors path="wafType.id" cssClass="errors" />
				</td>
			</tr>
		</tbody>
	</table>
	<br />
<c:choose>
<c:when test="${ waf.new }">
	<input id="addWafButton" type="submit" value="Add WAF" />
	<spring:url value="/wafs" var="wafUrl" />
</c:when>
<c:otherwise>
	<input id="updateWafButton" type="submit" value="Update WAF" />
	<spring:url value="/wafs/{wafId}" var="wafUrl">
		<spring:param name="wafId" value="${ waf.id }" />
	</spring:url>
</c:otherwise>
</c:choose>
	<span style="padding-left: 10px"><a id="cancelLink" href="${ fn:escapeXml(wafUrl) }">Cancel</a></span>
</form:form>
</body>

src/main/webapp/WEB-INF/views/wafs/index.jsp
<%@ include file="/common/taglibs.jsp"%>

<head>
	<title>WAFs</title>
</head>

<body id="wafs">
	<h2>WAFs</h2>
	
	<div id="helpText" style="width:630px;">
		A ThreadFix WAF is used to generate rules for a WAF or IDS/IPS program that is used to filter web traffic.
	</div>
	
	<table class="formattedTable">
		<thead>
			<tr>
				<th class="long first">Name</th>
				<th class="medium last">Type</th>
			</tr>
		</thead>
		<tbody id="wafTableBody">
		<c:if test="${ empty wafList }">
			<tr class="bodyRow">
				<td colspan="2" style="text-align:center;">No WAFs found.</td>
			</tr>
		</c:if>
		<c:forEach var="waf" items="${ wafList }">
			<tr class="bodyRow">
				<td class="details">
					<spring:url value="/wafs/{wafId}" var="wafUrl">
						<spring:param name="wafId" value="${ waf.id }" />
					</spring:url>
					<a href="${ fn:escapeXml(wafUrl) }">
						<c:out value="${ waf.name }"/>
					</a>
				</td>
				<td><c:out value="${ waf.wafType.name }"/></td>
			</tr>
		</c:forEach>
		</tbody>
	</table>
	
	<div style="padding-top:10px" id="link"><a id="addWafLink" href="<spring:url value="/wafs/new" />">Add WAF</a></div>
</body>